# Generated by Django 4.0.6 on 2022-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0002_rentclient_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentclient",
            name="paid",
        ),
        migrations.AddField(
            model_name="rentclient",
            name="last_payment",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="rentclient",
            name="payment_status",
            field=models.CharField(default="Pago", max_length=255),
        ),
    ]
