# Generated by Django 4.0.6 on 2022-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceclient",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
