# Generated by Django 4.0.6 on 2022-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0003_remove_insuranceclient_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceclient",
            name="payment_status",
            field=models.IntegerField(default=3),
        ),
    ]
